### ISSUE TITLE
Bug: DoH client is missing in-memory cache

### ISSUE THREAD

**Issue by lidel** [ipfs/service-worker-gateway#59]
Found the problem can be seen when opening http://localhost:3000/ipns/docs.ipfs.tech without subdomain isolation (e.g. commit 1ef00944c2e99b48207541d5602ebc0150cb512b).

Bunch of times `/ipfs/assets/fooo` is being resolved (separate problem, but will go away when I finish #30):

> ![image](https://github.com/ipfs-shipyard/helia-service-worker-gateway/assets/157609/893e25a3-a70b-4550-84b4-11257e3dac4b)

This edge case surfaced a weakness in our DoH implementation: no local cache.
And each time we trigger the same DNS lookup for `_dnslink.assets`:

>  ![image](https://github.com/ipfs-shipyard/helia-service-worker-gateway/assets/157609/3deac072-d184-4106-abd0-b464d186f474)

This works fast only because we added cache in https://github.com/ipshipyard/waterworks-infra/pull/30, but is wasteful and eats into the pool of HTTP request our SW can make.

We need to have in-memory cache which ideally respects TTL from DNS, or at least caches results for  1 minute before asking upstream for an update.

**Comment by SgtPooki** [comment]
this should be resolved with the latest helia-verified-fetch and new dns updates. will confirm and then resolve

**Comment by 2color** [comment]
I just tried with inbrowser.dev and it seems that even with https://github.com/ipfs/helia-verified-fetch/pull/19 merged and included in the latest release, caching is not working properly. For example see in the second screenshot the logs to the console, most times it isn't resolved from cache.  

![Screenshot 2024-03-26 at 1 02 20 pm](https://github.com/ipfs-shipyard/helia-service-worker-gateway/assets/1992255/8b02f844-2bb9-4b7a-9227-b0e3d8a05f6d)
![Screenshot 2024-03-26 at 1 06 24 pm](https://github.com/ipfs-shipyard/helia-service-worker-gateway/assets/1992255/d5c1b8a1-4d35-4d2a-9509-9660ff8f4855)


I'm gonna look into this.

**Comment by 2color** [comment]
https://github.com/ipfs/helia-verified-fetch/pull/34 should resolve this. 

I was under the false impression that we cache the DNSLink record in the datastore  inside `@helia/ipns`, but that doesn't seem to be the case.

**Comment by 2color** [comment]
Strange that even though we had a bug (resolved by https://github.com/ipfs/helia-verified-fetch/pull/34) with the cache in verified-fetch, it seems that `@multiformats/dns` used by `@helia/ipns` wasn't returning from its [own cache](https://github.com/multiformats/js-dns/blob/main/src/dns.ts#L48), which results in many DoH requests.

I'll investigate this

**Comment by SgtPooki** [comment]
we should be able to close this once the latest `@helia/ipns` is released

**Comment by SgtPooki** [comment]
helia ipns is released. we need to update verified-fetch and then update here.

https://github.com/ipfs/helia/releases/tag/ipns-v7.2.0

**Comment by SgtPooki** [comment]
This issue is resolved on `main`.

**Comment by 2color** [comment]
Also confirming that from my tests this is resolved!

**Comment by SgtPooki** [comment]
@aschmahmann reported issues with multiple dns-queries still, but we're having trouble reproducting.

Adin, can you provide the commit hash (found in HTML of root domain) of the site you're using, and a screenshot of what you're seeing for "multiple dns queries" ?

**Comment by aschmahmann** [comment]
@SgtPooki not able to see within the same browser request the HTML of the root domain to get the commit hash, but I've got this as the loaded js and there's a tag on the JS file name that IIUC should help with versioning.

<img width="915" alt="version" src="https://github.com/ipfs-shipyard/service-worker-gateway/assets/2733228/68b39d33-2db3-4ba1-86fa-a3b6770d3607">

and here are the multiple dns requests

<img width="915" alt="dns-queries" src="https://github.com/ipfs-shipyard/service-worker-gateway/assets/2733228/f4e6ec8a-4a07-4426-9a04-457622149c0e">

**Comment by SgtPooki** [comment]
@aschmahmann you should be able to go to `<url>/#/ipfs-sw-config` to get the config page, which still uses the same index.html, which will have the commit hash. That will make tracking things down a lot easier.

<img width="835" alt="image" src="https://github.com/ipfs-shipyard/service-worker-gateway/assets/1173416/9871e0a8-5668-4e28-8100-ddccf9f9eba5">

**Comment by SgtPooki** [comment]
@aschmahmann do you still get this error on inbrowser.dev?

**Comment by SgtPooki** [comment]
confirmed this is happening intermittently for Adin on latest. might be a race condition? might be CORS pre-flight being blocked causing issues? we need to dive in deeper, but it's a hard to repro problem that is inconsistent

**Comment by SgtPooki** [comment]
I believe this was fixed by https://github.com/ipfs/service-worker-gateway/pull/435 & https://github.com/ipfs/service-worker-gateway/pull/436

@aschmahmann (or anyone) can you confirm this is still happening on inbrowser.dev ?
